src/assets/styles/components/_game-debug.scss, src/assets/styles/components/_game-ui.scss, src/components/ui/debug/DebugButton.tsx, src/components/ui/debug/GameDebugToggleButton.tsx, src/game/manager/GameManager.ts, src/game/objects/Spam.ts, src/game/scenes/BootScene.ts, src/game/scenes/SplashscreenScene.ts, src/game/scenes/action/SpamGameScene.ts, src/store/GameDebugStore.ts, src/store/GameStore.ts, src/utils/enums.ts, src/utils/extensions.ts, src/utils/game.ts, src/utils/hooks.ts, src/utils/interfaces.ts
=> Refacto Spam game et gestion des scènes

package.json, src/assets/styles/components/debug/_debug-container.scss, src/components/Game.tsx, src/components/ui/GameUI.tsx, src/components/ui/Transition.tsx, src/components/ui/debug/DebugContainer.tsx, src/components/ui/debug/GameDebugStateList.tsx, src/game/manager/GameManager.ts, src/game/scenes/action/SpamGameScene.ts, src/index.tsx, src/phaser.d.ts, src/store/GameStore.ts, src/utils/anims.ts, src/utils/functions.ts, yarn.lock
=> Scene transitions

src/components/ui/GameUI.tsx, src/components/ui/MinigameUI.tsx, src/components/ui/Transition.tsx, src/components/ui/debug/GameDebugButtonsToolbar.tsx, src/components/ui/debug/GameDebugToggleButton.tsx, src/components/ui/games/MinigameToolbar.tsx, src/components/ui/games/RemainingTime.tsx, src/game/manager/GameManager.ts, src/game/objects/Spam.ts, src/game/scenes/BaseScene.ts, src/game/scenes/BootScene.ts, src/game/scenes/SplashscreenScene.ts, src/game/scenes/action/SpamGameScene.ts, src/store/GameDebugStore.ts, src/store/GameStore.ts, src/utils/constants.ts, src/utils/enums.ts, src/utils/game.ts, src/utils/hooks.ts, tslint.json
=> UI de base des mini-jeux

src/components/ui/GameUI.tsx, src/components/ui/MinigameUI.tsx, src/components/ui/Transition.tsx, src/components/ui/debug/GameDebugButtonsToolbar.tsx, src/components/ui/debug/GameDebugToggleButton.tsx, src/components/ui/games/MinigameToolbar.tsx, src/components/ui/games/RemainingTime.tsx, src/game/manager/GameManager.ts, src/game/objects/Spam.ts, src/game/scenes/BaseScene.ts, src/game/scenes/BootScene.ts, src/game/scenes/MinigameScene.ts, src/game/scenes/SplashscreenScene.ts, src/game/scenes/action/SpamGameScene.ts, src/store/GameDebugStore.ts, src/store/GameStore.ts, src/utils/constants.ts, src/utils/enums.ts, src/utils/game.ts, src/utils/hooks.ts, tslint.json
- Utilisé par tous les prochains mini-jeux, et implémente des méthodes de bases tel que `onSuccess`, qui doit être appelé quand le mini-jeu est considéré comme gagné, et `onFailure` pour l'inverse
=> Spam minigame

src/components/Game.tsx, src/components/GameDebug.tsx, src/components/ui/debug/DebugContainer.tsx, src/components/ui/debug/GameDebugConfigPanel.tsx, src/components/ui/debug/GameDebugMinigamePicker.tsx, src/components/ui/debug/GameDebugStateList.tsx, src/utils/interfaces.ts
Correction du picker minigame afin de garder sa position lorsqu'il n'est plus affiché
=> [FIX] -  Minigame picker position

src/game/scenes/action/SandwichGameScene.ts
=> Fix disable controls on win event

src/game/scenes/action/SandwichGameScene.ts
=> [HOTFIX] - Sandwich game ending

src/components/ui/debug/GameDebugButtonsToolbar.tsx, src/components/ui/debug/GameDebugToggleSoundsButton.tsx, src/game/manager/AudioManager.ts, src/store/GameStore.ts
Ajout d'un bouton permettant de mute le son du jeu
=> [DEBUG] - Mute sound button

src/App.tsx, src/assets/styles/app.scss, src/components/Game.tsx, src/components/Introduction.tsx, src/components/ui/debug/GameDebugToggleButton.tsx, src/game/manager/GameManager.ts, src/game/scenes/BaseScene.ts, src/game/scenes/BootScene.ts, src/index.tsx, src/store/GameStore.ts, src/utils/game.ts
Ajout de la page d'accueil du site. Elle preload le jeu en fond, et ne rends disponible le bouton pour lancer le jeu que lorsqu'il a été complètement chargé. L'intégration n'est pas encore faite. Le jeu se lance donc désormais via un appui sur un bouton et permet donc deux choses primordiales : le **lancement correct de la Web Audio API** (Chrome requiert une interaction utilisateur afin de démarrer le contexte audio), mais aussi de demander le plein écran au client, une fois de plus disponible qu'après une **action explicite** de l'utilisateur.
A noter que en environnement de dev, le jeu se démarre tout seul afin d'accélérer le processus de développement.
- Utilisée afin de réagir au clic sur le bouton de démarrage, sur la page d'accueil
=> [FEAT] - Introduction

src/game/objects/Spam.ts
=> Fix yo animation size

src/game/scenes/action/TrafficGameScene.ts
=> Fix issues when game restart

src/components/ui/modals/PauseModal.tsx, src/store/GameStore.ts
Le bouton "Quit" dans la pause redémarre désormais le jeu. Correction du detune de la musique qui était un peu trop haut lorsque le jeu redémarrait.
=> [FIX] - Quit pause button

package.json, src/components/ui/LeaderboardsUI.tsx, src/components/ui/PostMinigameUI.tsx, src/components/ui/games/RemainingTime.tsx, src/components/ui/leaderboards/LeaderboardsEntry.tsx, src/components/ui/leaderboards/LeaderboardsTable.tsx, src/game/scenes/MinigameScene.ts, src/store/GameStore.ts, src/store/LeaderboardsStore.ts, src/utils/enums.ts, yarn.lock
Modification du système de scoring. Avant, le score était simplement le temps passé en mini-jeu. Cependant, cela n'était pas pertinent car on récompensait les personnes qui passent du temps sur un mini-jeu. Or, plus un joueur finit un mini-jeu rapidement, plus il doit être récompensé. 
De ce fait, le score n'est plus symbolisé par une durée (sous la forme **xx**:**xx**) mais plutôt par un nombre comme le font les jeux rétros.
=> [UPDATE] - Scoring system

src/game/scenes/action/SubwayGameScene.ts
=> - Fixed class variables reset

package-lock.json, src/game/scenes/action/ElevatorGameScene.ts
=> deleting a recalcitrant comment

src/game/scenes/action/SubwayGameScene.ts
=> [FIX] - Subway game error on game end

src/components/ui/GameButton.tsx, src/components/ui/modals/SettingsModal.tsx, src/game/manager/GameManager.ts
Correction de bugs propre à Safari
=> [FIX] - Safari bugs

src/components/ui/modals/SettingsModal.tsx
=> - Fix broken styles modal

src/components/ui/BigButton.tsx, src/components/ui/GameButton.tsx, src/components/ui/games/GamePauseButton.tsx, src/components/ui/leaderboards/LeaderboardsUsernameInputBlock.tsx, src/utils/constants.ts
Ajout de la vibration sur les boutons permettant d'entrer son nom d'utilisateur dans le leaderboard, et ajout d'une constante afin de stocker le temps de vibration d'un bouton.
=> [FIX] - Score input vibration

public/index.html, public/static/assets/sprites/pack.json, src/App.tsx, src/assets/styles/app.scss, src/components/ui/notifications/Notification.tsx, src/components/ui/notifications/NotificationsContainer.tsx, src/registerServiceWorker.ts, src/utils/enums.ts, src/utils/functions.ts, src/utils/hooks.ts, src/utils/keyframes.ts
Ajout du support de notifications in-game.
=> [FEAT] - Notifications

src/game/scenes/action/ElevatorGameScene.ts, src/game/scenes/action/PasswordGameScene.ts, src/game/scenes/action/SpamGameScene.ts, src/game/scenes/action/SubwayGameScene.ts
Remodification des couleurs des mini jeux
=> [FIX] - Randomize color minigame

src/components/ui/MinigameGuideline.tsx, src/game/scenes/action/ElevatorGameScene.ts, src/game/scenes/action/PasswordGameScene.ts, src/game/scenes/action/SandwichGameScene.ts, src/game/scenes/action/SpamGameScene.ts, src/game/scenes/action/SubwayGameScene.ts, src/game/scenes/action/TrafficGameScene.ts
=> Improve minigame guide

src/components/ui/DeathscreenUI.tsx
Fix des marges sur le deathscreen
=> - Fix padding-top deathscreen

src/assets/data.json, src/components/Introduction.tsx
-[x] Quick fix data
-[x] Changed font size intro
=> - Quick fix data
